spring.application.name=rifas-publicas
spring.datasource.url=jdbc:postgresql://localhost:5432/rifas_db
spring.datasource.username=postgres
spring.datasource.password=12345

# Configuración de JPA / Hibernate con Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-on-validation-error=true
spring.flyway.clean-disabled=false

server.port=${PORT:8080}
server.address=0.0.0.0

# Configuracion de correo electrónico para recuperación de contraseña
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adipworkspace@gmail.com
spring.mail.password=mavn qrhr ngso zbef
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Añade estos timeouts para evitar que la app se congele si la red bloquea el puerto 587
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# URL base de la aplicación (Local)
app.base-url=http://localhost:8080
