spring.application.name=rifas-publicas
spring.datasource.url=jdbc:postgresql://localhost:5432/rifas_db
spring.datasource.username=postgres
spring.datasource.password=12345

# Configuración de JPA / Hibernate con Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-on-validation-error=false
spring.flyway.clean-disabled=true

server.port=${PORT:8080}
server.address=0.0.0.0

# Esto es solo una plantilla. La llave real se inyecta desde el sistema local.
resend.api.key=${RESEND_API_KEY}

# URL base de la aplicación (Local)
app.base-url=http://localhost:8080
